application:
  environment: Pedido Producao
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/servico_pedidos?createDatabaseIfNotExist=true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
eureka:
  instance:
    instance-id: ${spring.application.name}::${spring.application.instance_id:${random.value}}