application:
  environment: Pedido Desenvolvimento
spring:
  kafka:
    listener:
      ack-mode: manual_immediate
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-server: localhost:29092
      group-id: pedidos-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: embedded
    username: sa
    password:
    url: jdbc:h2:mem:pedidosdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      platform: h2
      data-locations: classpath:data-h2.sql
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
eureka:
  instance:
    instance-id: ${spring.application.name}::${spring.application.instance_id:${random.value}}