application:
  environment: Envio Desenvolvimento
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: embedded
    username: sa
    password:
    url: jdbc:h2:mem:enviodb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      platform: h2
      data-locations: classpath:data-h2.sql
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
eureka:
  instance:
    instance-id: ${spring.application.name}::${spring.application.instance_id:${random.value}}